twitance/config/routes.rb
Twitance::Application.routes.draw do
  resources :twitters  
  match 'facets' => 'twitters#facets'

    root :to => 'twitters#new'

end

twitance/app/models/twitter.rb
class Twitter < ActiveRecord::Base
	include Tire::Model::Search
	include Tire::Model::Callbacks
  	attr_accessible :handle, :tweet

  	mapping do 
  		indexes :handle,	:index => :not_analyzed
  		indexes :tweet, 	:analyzer => 'snowball'
  	end
  	
  	

	
end

twitance/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

twitance/app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
	def new
		render "new"
	end


	def create 
		@tweet = Twitter.new(params[:tweet])
		@tweet.save
		redirect_to @tweet
		#render text: params[:tweet].inspect
	end


	def facets
		@sea = Twitter.search do 
			facet 'word', :global => true do
        		terms :tweet
      		end
			#facet('word') {}
		end

		if @sea
			p "sae exists "
			p "#{@sea.facets['word']['terms'][0]['term']}"
			p "#{@sea.facets['word']['terms'][0]['count']}"
		else
			p "try hasd "
		end		
	end
	#end

	def show
		@tweet = Twitter.find(params[:id])
		if @tweet
			p "tweet exit"
		else 
			p "not exits"
		end
		#@sea = Twitter.search(params)#all #search(:facet => { })

		@sea = Twitter.search do 
			facet 'word', :global => true do
        		terms :tweet
      		end
			#facet('word') {}
		end

		if @sea
			p "sae exists "
			p "#{@sea.facets['word']['terms'][0]['term']}"
			p "#{@sea.facets['word']['terms'][0]['count']}"
		else
			p "try hasd "
		end		
end
end

twitance/app/helpers/application_helper.rb
module ApplicationHelper
end

twitance/app/helpers/twitters_helper.rb
module TwittersHelper
end

twitance/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitance</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

twitance/app/views/twitters/facets.html.haml
		
%strong word count
%table{:cellpadding => "10"}
- @sea.facets['word']["terms"].each do |f|
		
	%br
	%tr
		%td
		%strong= f['term']
		%td
		%strong= f['count']
	%br


%br

twitance/app/views/twitters/new.html.haml
= form_for :tweet, url: twitters_path do |f|
  %p
    = f.label :handle
    %br
      = f.text_field :handle
  %p
    = f.label :tweet
    %br
      = f.text_area :tweet
  %p
    = f.submit 

twitance/app/views/twitters/show.html.haml
%p
	%strong Handle
	%br
	= @tweet.handle
%p
	%strong Tweet
	%br
	= @tweet.tweet

	%br
	%hr
	%strong From elasticsearch all data
	%br
	- @sea.each do |t|
		%b handle 
		%br
		= t.handle
		%br
		= t.tweet
		%br
	%br
	%a{:href => "/facets"} facets count
	

%br